# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: authtoken/authtoken.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 7, 35, 1, "", "authtoken/authtoken.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x19\x61uthtoken/authtoken.proto\x12\tauthtoken"+\n\x1aValidateAccessTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t"\x80\x01\n\x1bValidateAccessTokenResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\x03\x12\x10\n\x08username\x18\x04 \x01(\t\x12\x12\n\nis_premium\x18\x05 \x01(\x08\x12\x0c\n\x04tier\x18\x06 \x01(\t2{\n\x13\x41uthTokenValidation\x12\x64\n\x13ValidateAccessToken\x12%.authtoken.ValidateAccessTokenRequest\x1a&.authtoken.ValidateAccessTokenResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "authtoken.authtoken_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_VALIDATEACCESSTOKENREQUEST"]._serialized_start = 40
    _globals["_VALIDATEACCESSTOKENREQUEST"]._serialized_end = 83
    _globals["_VALIDATEACCESSTOKENRESPONSE"]._serialized_start = 86
    _globals["_VALIDATEACCESSTOKENRESPONSE"]._serialized_end = 214
    _globals["_AUTHTOKENVALIDATION"]._serialized_start = 216
    _globals["_AUTHTOKENVALIDATION"]._serialized_end = 339
# @@protoc_insertion_point(module_scope)
