repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3.11
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
        args: [--fix]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        files: ^Module2/TDD-Based-Weather-API/
        args: [--strict]
        additional_dependencies: ["pydantic", "pytest", "fastapi", "httpx", "starlette"]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: Module2/TDD-Based-Weather-API/venv/bin/pytest
        language: system
        types: [python]
        pass_filenames: false
        args: ["--rootdir=Module2/TDD-Based-Weather-API", "--ignore=Module2/secure-auth-service"]
