# Generated by Django 6.1 on 2026-08-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=64, unique=True)),
            ],
            options={
                "db_table": "tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="URL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("original_url", models.URLField(max_length=2048)),
                ("short_code", models.CharField(db_index=True, max_length=10, unique=True)),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("owner_id", models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ("click_count", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("last_accessed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, db_table="urls_tags", related_name="urls", to="shortener.tag"
                    ),
                ),
            ],
            options={
                "db_table": "urls",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["owner_id"], name="urls_owner_i_e0a75f_idx"),
                    models.Index(fields=["is_active"], name="urls_is_acti_ad181e_idx"),
                    models.Index(fields=["original_url"], name="urls_origina_dd0764_idx"),
                ],
            },
        ),
    ]
