# Generated by Django 6.1 on 2026-08-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Click",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("short_code", models.CharField(db_index=True, max_length=10)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("country", models.CharField(blank=True, default="", max_length=2)),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("referer", models.URLField(blank=True, default="", max_length=2048)),
                ("clicked_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "clicks",
                "ordering": ["-clicked_at"],
                "indexes": [
                    models.Index(
                        fields=["short_code", "-clicked_at"], name="clicks_short_c_c675d4_idx"
                    ),
                    models.Index(
                        fields=["country", "-clicked_at"], name="clicks_country_4a798f_idx"
                    ),
                ],
            },
        ),
    ]
