# Generated by Django 6.1 on 2026-08-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_outstandingtoken_on_delete_set_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="tier",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("basic", "Basic"),
                    ("pro", "Pro"),
                    ("enterprise", "Enterprise"),
                ],
                default="free",
                max_length=20,
            ),
        ),
    ]
