# Generated by Django 6.1 on 2026-08-26 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shortener", "0003_url_owner_on_delete_cascade"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=64, unique=True)),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "db_table": "tags",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="url",
            name="click_count",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="url",
            name="expires_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="url",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="url",
            name="last_accessed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="url",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="url",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="url",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="urls",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Click",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("referer", models.URLField(blank=True, default="", max_length=2048)),
                ("country", models.CharField(blank=True, default="", max_length=2)),
                ("clicked_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clicks",
                        to="shortener.url",
                    ),
                ),
            ],
            options={
                "verbose_name": "Click",
                "verbose_name_plural": "Clicks",
                "db_table": "clicks",
                "ordering": ["-clicked_at"],
            },
        ),
        migrations.AddField(
            model_name="url",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="urls", to="shortener.tag"),
        ),
        migrations.AddIndex(
            model_name="url",
            index=models.Index(fields=["owner", "-created_at"], name="urls_owner_i_513c55_idx"),
        ),
        migrations.AddIndex(
            model_name="url",
            index=models.Index(fields=["-click_count"], name="urls_click_c_0828dc_idx"),
        ),
        migrations.AddIndex(
            model_name="url",
            index=models.Index(fields=["is_active", "expires_at"], name="urls_is_acti_847f2f_idx"),
        ),
        migrations.AddIndex(
            model_name="click",
            index=models.Index(fields=["url", "-clicked_at"], name="clicks_url_id_afa311_idx"),
        ),
        migrations.AddIndex(
            model_name="click",
            index=models.Index(fields=["country", "-clicked_at"], name="clicks_country_4a798f_idx"),
        ),
    ]
