# Generated by Django 6.1 on 2026-08-26 21:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shortener", "0004_enhanced_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="click",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="url",
            options={"managed": False},
        ),
    ]
