# Generated by Django 6.1 on 2026-08-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    """Adopt the shortener tables as Django-managed.

    The ``urls``/``tags``/``clicks``/``urls_tags`` tables were previously
    owned by Alembic (SQLAlchemy).  This migration flips the Django models
    to ``managed`` and records the model state Django expects, while using
    idempotent ``database_operations`` so it is a no-op on an existing DB
    that already carries the schema.
    """

    dependencies = [
        ("shortener", "0007_alter_click_options_alter_tag_options_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="click",
                    name="city",
                    field=models.CharField(blank=True, default="", max_length=100),
                ),
                migrations.AlterField(
                    model_name="url",
                    name="tags",
                    field=models.ManyToManyField(
                        blank=True,
                        db_table="urls_tags",
                        related_name="urls",
                        to="shortener.tag",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE clicks ADD COLUMN IF NOT EXISTS "
                        "city VARCHAR(100) NOT NULL DEFAULT ''"
                    ),
                    reverse_sql=("ALTER TABLE clicks DROP COLUMN IF EXISTS city"),
                ),
                migrations.RunSQL(
                    sql=(
                        "CREATE TABLE IF NOT EXISTS urls_tags ("
                        "  id BIGSERIAL PRIMARY KEY,"
                        "  url_id BIGINT NOT NULL REFERENCES urls(id) ON DELETE CASCADE,"
                        "  tag_id BIGINT NOT NULL REFERENCES tags(id) ON DELETE CASCADE,"
                        "  UNIQUE (url_id, tag_id)"
                        ")"
                    ),
                    reverse_sql="DROP TABLE IF EXISTS urls_tags CASCADE",
                ),
            ],
        ),
    ]
