# Generated by Django 6.1 on 2026-08-29 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shortener", "0008_click_city_alter_url_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="url",
            name="urls_owner_i_513c55_idx",
        ),
        migrations.RemoveIndex(
            model_name="url",
            name="urls_click_c_0828dc_idx",
        ),
        migrations.RemoveIndex(
            model_name="url",
            name="urls_is_acti_847f2f_idx",
        ),
        migrations.AlterField(
            model_name="url",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="url",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="urls",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="url",
            index=models.Index(fields=["owner"], name="urls_owner_i_e0a75f_idx"),
        ),
        migrations.AddIndex(
            model_name="url",
            index=models.Index(fields=["is_active"], name="urls_is_acti_ad181e_idx"),
        ),
        migrations.AddIndex(
            model_name="url",
            index=models.Index(fields=["original_url"], name="urls_origina_dd0764_idx"),
        ),
    ]
