# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from authtoken import authtoken_pb2 as authtoken_dot_authtoken__pb2

GRPC_GENERATED_VERSION = "1.83.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in authtoken/authtoken_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class AuthTokenValidationStub:
    """Internal service-to-service contract between the auth service and its
    callers (shortener, analytics). Neither of those services has a `users`
    table or the JWT signing key; verifying an access token — and reading
    the identity claims embedded in it — means asking auth over gRPC
    instead of decoding the token locally.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ValidateAccessToken = channel.unary_unary(
            "/authtoken.AuthTokenValidation/ValidateAccessToken",
            request_serializer=authtoken_dot_authtoken__pb2.ValidateAccessTokenRequest.SerializeToString,
            response_deserializer=authtoken_dot_authtoken__pb2.ValidateAccessTokenResponse.FromString,
            _registered_method=True,
        )


class AuthTokenValidationServicer:
    """Internal service-to-service contract between the auth service and its
    callers (shortener, analytics). Neither of those services has a `users`
    table or the JWT signing key; verifying an access token — and reading
    the identity claims embedded in it — means asking auth over gRPC
    instead of decoding the token locally.

    """

    def ValidateAccessToken(self, request, context):
        """Verifies an access token's signature, expiry, and type, returning the
        identity claims embedded in it if valid.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_AuthTokenValidationServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ValidateAccessToken": grpc.unary_unary_rpc_method_handler(
            servicer.ValidateAccessToken,
            request_deserializer=authtoken_dot_authtoken__pb2.ValidateAccessTokenRequest.FromString,
            response_serializer=authtoken_dot_authtoken__pb2.ValidateAccessTokenResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "authtoken.AuthTokenValidation", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("authtoken.AuthTokenValidation", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class AuthTokenValidation:
    """Internal service-to-service contract between the auth service and its
    callers (shortener, analytics). Neither of those services has a `users`
    table or the JWT signing key; verifying an access token — and reading
    the identity claims embedded in it — means asking auth over gRPC
    instead of decoding the token locally.

    """

    @staticmethod
    def ValidateAccessToken(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/authtoken.AuthTokenValidation/ValidateAccessToken",
            authtoken_dot_authtoken__pb2.ValidateAccessTokenRequest.SerializeToString,
            authtoken_dot_authtoken__pb2.ValidateAccessTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
