# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from urlownership import ownership_pb2 as urlownership_dot_ownership__pb2

GRPC_GENERATED_VERSION = "1.83.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in urlownership/ownership_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class ShortenerOwnershipStub:
    """Internal service-to-service contract between the analytics and shortener
    services. The analytics service has no `urls` table of its own; when it
    needs to check existence/ownership for premium analytics it calls this
    RPC. This replaces the prior synchronous HTTP endpoint
    (GET /api/v1/internal/urls/{short_code}/) with a faster, strongly-typed
    gRPC call.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOwner = channel.unary_unary(
            "/urlownership.ShortenerOwnership/GetOwner",
            request_serializer=urlownership_dot_ownership__pb2.GetOwnerRequest.SerializeToString,
            response_deserializer=urlownership_dot_ownership__pb2.GetOwnerResponse.FromString,
            _registered_method=True,
        )


class ShortenerOwnershipServicer:
    """Internal service-to-service contract between the analytics and shortener
    services. The analytics service has no `urls` table of its own; when it
    needs to check existence/ownership for premium analytics it calls this
    RPC. This replaces the prior synchronous HTTP endpoint
    (GET /api/v1/internal/urls/{short_code}/) with a faster, strongly-typed
    gRPC call.

    """

    def GetOwner(self, request, context):
        """Returns whether a short code exists and, if so, its id and owner id."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ShortenerOwnershipServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetOwner": grpc.unary_unary_rpc_method_handler(
            servicer.GetOwner,
            request_deserializer=urlownership_dot_ownership__pb2.GetOwnerRequest.FromString,
            response_serializer=urlownership_dot_ownership__pb2.GetOwnerResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "urlownership.ShortenerOwnership", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("urlownership.ShortenerOwnership", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class ShortenerOwnership:
    """Internal service-to-service contract between the analytics and shortener
    services. The analytics service has no `urls` table of its own; when it
    needs to check existence/ownership for premium analytics it calls this
    RPC. This replaces the prior synchronous HTTP endpoint
    (GET /api/v1/internal/urls/{short_code}/) with a faster, strongly-typed
    gRPC call.

    """

    @staticmethod
    def GetOwner(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/urlownership.ShortenerOwnership/GetOwner",
            urlownership_dot_ownership__pb2.GetOwnerRequest.SerializeToString,
            urlownership_dot_ownership__pb2.GetOwnerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
