# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: urlownership/ownership.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 7, 35, 1, "", "urlownership/ownership.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1curlownership/ownership.proto\x12\x0curlownership"%\n\x0fGetOwnerRequest\x12\x12\n\nshort_code\x18\x01 \x01(\t"D\n\x10GetOwnerResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x12\x0e\n\x06url_id\x18\x02 \x01(\x03\x12\x10\n\x08owner_id\x18\x03 \x01(\x03\x32_\n\x12ShortenerOwnership\x12I\n\x08GetOwner\x12\x1d.urlownership.GetOwnerRequest\x1a\x1e.urlownership.GetOwnerResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "urlownership.ownership_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_GETOWNERREQUEST"]._serialized_start = 46
    _globals["_GETOWNERREQUEST"]._serialized_end = 83
    _globals["_GETOWNERRESPONSE"]._serialized_start = 85
    _globals["_GETOWNERRESPONSE"]._serialized_end = 153
    _globals["_SHORTENEROWNERSHIP"]._serialized_start = 155
    _globals["_SHORTENEROWNERSHIP"]._serialized_end = 250
# @@protoc_insertion_point(module_scope)
