# Generated by Django 5.0.14 on 2026-08-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="URL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("original_url", models.URLField(max_length=2048)),
                ("short_code", models.CharField(db_index=True, max_length=10, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "URL",
                "verbose_name_plural": "URLs",
                "db_table": "urls",
                "ordering": ["-created_at"],
            },
        ),
    ]
