# Generated by Django 6.1 on 2026-08-28 21:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shortener", "0006_seed_default_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="click",
            options={"ordering": ["-clicked_at"]},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="url",
            options={"ordering": ["-created_at"]},
        ),
    ]
